### ISSUE TITLE
Is this updated to work with latest xcode and swift? i'm getting errors for overriding instance method optional result type

### ISSUE THREAD

**Issue by rlam3** [ecerney/CollectionViewWaterfallLayout#11]
Is this updated to work with latest xcode and swift? i'm getting errors for overriding instance method optional result type

**Comment by ecerney** [comment]
@rlam3 I'll check as soon as I can to see if its up-to-date

**Comment by rlam3** [comment]
@ecerney I think I just had some outdated cocoapod I forgot to update. I think it should be fixed now. :) thanks!
