### ISSUE TITLE
Will there be a swift 3 version of this?

### ISSUE THREAD

**Issue by rlam3** [ecerney/CollectionViewWaterfallLayout#22]
Will there be a swift 3 version of this?

**Comment by ostatnicky** [comment]
You can use for now the branch from pull request #23

**Comment by ostatnicky** [comment]
For example this way:
```
pod 'CollectionViewWaterfallLayout', :git => 'https://github.com/ostatnicky/CollectionViewWaterfallLayout.git', :branch => 'feature/swift3'
```

**Comment by rlam3** [comment]
@ostatnicky When will the release be out?

**Comment by AFcgi** [comment]
Do you merge the Swift 3 support sometime?

**Comment by ecerney** [comment]
Sorry for all the delays. Just opened a PR for Swift 5 so closing the issue
