### ISSUE TITLE
Cocoapods error?

### ISSUE THREAD

**Issue by rlam3** [ecerney/CollectionViewWaterfallLayout#5]
I'm getting the following errors when using cocoapods following your demo:

Use of unresolved identifier 'CollectionViewWatefallElelementKindSectionHeader'
Use of unresolved identifier 'CollectionViewWatefallElelementKindSectionFooter'

Any reason why this may be?

Would it be possible for you to make a quick demo app with the coacopod ?

**Comment by ecerney** [comment]
@rlam3 Did you resolve this already?

**Comment by rlam3** [comment]
I got it working with making the header and footer elements publicly accessible.

https://github.com/rlam3/CollectionViewWaterfallLayout/blob/master/CollectionViewWaterfallLayout.swift

**Comment by ecerney** [comment]
Thanks for finding that. I just updated the repo and podspec, so should work now.
