### ISSUE TITLE
swift 2.0 update error

### ISSUE THREAD

**Issue by sunchengbo** [ecerney/CollectionViewWaterfallLayout#6]
When i update xcode to 7.0 ,this will throw many erros. I wish you to update 'CollectionViewWaterfallLayout', thank you very much.

**Comment by GnuRant** [comment]
+1

**Comment by ecerney** [comment]
@sunchengbo @GnuRant Sorry I haven't updated this in a while, will get an update up asap.

**Comment by yurijmi** [comment]
+1

**Comment by yurijmi** [comment]
Fixed everything in #7

**Comment by sunchengbo** [comment]
？

**Comment by yurijmi** [comment]
Made a pull request ;)

**Comment by sunchengbo** [comment]
I am a Chinese, you say that the drop-down refresh

**Comment by yurijmi** [comment]
Your translator is wrong, if you using one. I said that I updated the code so it runs on Xcode 7 without issues

**Comment by sunchengbo** [comment]
I didn't find you where is the updated version

**Comment by yurijmi** [comment]
It's not here until repo's author approves it. For now you can use this in your podfile
```pod 'CollectionViewWaterfallLayout', git: 'https://github.com/yurijmi/CollectionViewWaterfallLayout.git'```

**Comment by sunchengbo** [comment]
With the new address you gave me is you updated on yao, because I see you or to the new version 1.2, so there is no

**Comment by sunchengbo** [comment]
你跟新的'CollectionViewWaterfallLayout'我跟新过后在swift2.0中就可以使用了对么

**Comment by yurijmi** [comment]
I didn't understood anything that you said. Is it working for you?

**Comment by sunchengbo** [comment]
We can make friends, what social software do you use

**Comment by yurijmi** [comment]
Twitter, FaceBook, VK. what you prefer?

**Comment by sunchengbo** [comment]
Social software can't use you say, I can only use QQ or email

**Comment by sunchengbo** [comment]
I thank you very much but my English is poor

**Comment by yurijmi** [comment]
It is okay. My email is in my GitHub profile

**Comment by sunchengbo** [comment]
I might use translation software and your communication is not the same

**Comment by sunchengbo** [comment]
I know, thank you, I hope you can also use QQ, we make friends

**Comment by yurijmi** [comment]
QQ is not available in English nor in my native language, sorry. Email me if you like

**Comment by sunchengbo** [comment]
Thank you very much, although our language barrier, but I still thank you very much

**Comment by yurijmi** [comment]
You're welcome. I needed this too ;)

**Comment by sunchengbo** [comment]
I wish you guys a happy life

**Comment by yurijmi** [comment]
Thanks. Wish you too
